//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterOfFixAssets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetsP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetsP()
        {
            this.Detail_Master = new HashSet<Detail_Master>();
            this.AssetTransactions = new HashSet<AssetTransaction>();
        }
    
        public int item_ID { get; set; }
        public string item_name { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<int> status { get; set; } = 1;
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Master> Detail_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetTransaction> AssetTransactions { get; set; }
        public virtual CategoryMaster CategoryMaster { get; set; }
    }
}
