//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterOfFixAssets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTransaction
    {
        public int TransacId { get; set; }
        public int D_ID { get; set; }
        public Nullable<int> Item_Id { get; set; }
        public string UserName { get; set; }
        public string Roomno { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    
        public virtual AssetsP AssetsP { get; set; }
        public virtual Detail_Master Detail_Master { get; set; }
    }
}
