//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterOfFixAssets.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Detail_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Detail_Master()
        {
            this.AssetTransactions = new HashSet<AssetTransaction>();
        }
    
        public int D_ID { get; set; }
        public Nullable<int> item_ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public string Bill_No { get; set; }
        //[DisplayFormat(DataFormatString = "{dd MMM yyyy}")]
        public Nullable<System.DateTime> Bill_Date { get; set; }
        public string Cost { get; set; }
        public string RoomNo { get; set; }
        public string User_Name { get; set; }
        public string Item_Name { get; set; }
        public string Model_SlNo { get; set; }
        public string File_No { get; set; }
        public string Category { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remarks { get; set; }
        public string SupplierName { get; set; }
    
        public virtual AssetsP AssetsP { get; set; }
        public virtual SuppllierP SuppllierP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetTransaction> AssetTransactions { get; set; }
        public int Flag { get; set; }=0;
        [NotMapped]
        public string CombinedValue;
        [NotMapped]
        public string selectedValue { get
            {
                return User_Name + '|'+ RoomNo;
            }
            set
            {
                this.CombinedValue = value;
            }
        }
       [NotMapped]
       public string userlist { get; set; }
    }
}
