//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterOfFixAssets.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityConfig : DbContext
    {
        public EntityConfig()
            : base("name=EntityConfig")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssetsP> AssetsPs { get; set; }
        public virtual DbSet<CategoryMaster> CategoryMasters { get; set; }
        public virtual DbSet<Detail_Master> Detail_Master { get; set; }
        public virtual DbSet<SuppllierP> SuppllierPs { get; set; }
        public virtual DbSet<History_Master> History_Master { get; set; }
        public virtual DbSet<AssetTransaction> AssetTransactions { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
    }
}
