//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterOfFixAssets.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UserMaster
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Designation { get; set; }
        public string RoomNo { get; set; }
        public Nullable<int> Status { get; set; }
        [NotMapped]
        public string selectedValue
        {
            get
            {
                return UserName + '|' + RoomNo;
            }
        }
    }
}
